### PR TITLE
fix(IconLibrary): add 20/24 sizes

### LINKED ISSUE #1325: Icon Library ≠ icon assets found in carbon-elements; "undefined" category displayed
## Detailed description

Icons listed @ https://next.carbondesignsystem.com/guidelines/iconography/library are not consistent with what's found in https://github.com/IBM/carbon-elements/tree/master/packages/icons/src/svg

**Expected Behavior:**
 Headings for 16, 20, 24, 32 and Scaled from 32; `16x16` = contents of https://github.com/IBM/carbon-elements/tree/master/packages/icons/src/svg/16; `20x20` = contents of https://github.com/IBM/carbon-elements/tree/master/packages/icons/src/svg/20; `24x24`= contents of https://github.com/IBM/carbon-elements/tree/master/packages/icons/src/svg/24; `32x32`= contents of https://github.com/IBM/carbon-elements/tree/master/packages/icons/src/svg/32 .

`Scaled from 32` = all of the generated assets (sizes scaled from 32.

Disregard glyphs found in root of https://github.com/IBM/carbon-elements/tree/master/packages/icons/src/svg

**Actual Behavior:**
`16x16` ≠ https://github.com/IBM/carbon-elements/tree/master/packages/icons/src/svg/16 (107 icons displayed, 111 in the repo)
no `20x20`
no `24x24`
`32x32` has ?, repo has 640
`undefined` has a bunch including actual 20x20s, 24x24s, and scaled 32s

## Steps to reproduce the issue

1. Navigate to https://next.carbondesignsystem.com/guidelines/iconography/library
2. observe actual behavior

### PR DESCRIPTION
**Pull request by asudoh**
ref #1325.

#### Changelog

**Changed**

- Fixed icon size list in iconography page to capture missing sizes.

### CODE REVIEW

File: src/components/IconLibrary/IconLibrary.js [hunk 1]
```diff
@@ -2,7 +2,7 @@ import React from 'react';
 import { Search, Loading } from 'carbon-components-react';
 import IconEmptyState from '../IconEmptyState';
 
-const sizes = ['16', '32', 'Glyph'];
+const sizes = ['16', '20', '24', '32', 'Glyph'];
```
Comment (shixiedesign) [inline src/components/IconLibrary/IconLibrary.js]: `const sizes = ['16', '20', '24', '32'];`
This would remove the Glyph section all together. Is that what you want? @chrisconnors-ibm

**Comment by shixiedesign** [comment]
I'd merge this PR even though it doesn't fix the #1325 just because it's still an improvement from today. 

Just to clarify @asudoh, I think #1325 is requiring the icon library icons to be pulled dynamically from `carbon-elements` repo. Based on this PR's preview link, the icons are still not the same set as those in `carbon-elements` repo.

**Comment by asudoh** [comment]
@shixiedesign I saw with @jeoffw that the code incorporates the icons from `@carbon/icons-react`. Just bumped the dependency so it takes the latest. Not sure if @chrisconnors-ibm wants to ignore all fires right in https://github.com/carbon-design-system/carbon/tree/master/packages/icons/src/svg or something else.

**Comment by asudoh** [comment]
Failing tests due to carbon-design-system/carbon-elements#327, dropping a note to @alisonjoseph to see how she wants to move forward with it. Seems that we need to add some build settings, and wondering if such build settings addition is something @alisonjoseph would be comfortable with maintaining.

**Comment by alisonjoseph** [comment]
@joshblack FYI

**Comment by asudoh** [comment]
Thanks @shixiedesign for reviewing - Until we get a conclusion of the build configuration discussion, let me back out `@carbon/icons-react` upgrade for now.

**Comment by alisonjoseph** [comment]
After talking to @joshblack looks like work being done in the Icon project will hopefully update what we need to in the icons package to add the icon entrypoint back in, so we can't pull from the latest until that happens.

**Comment by jeoffw** [comment]
Please go ahead and merge the addition of 20/24 sizes, since that is an improvement over the status quo.
