### PR TITLE
Make side nav keyboard accessible.

### LINKED ISSUE #258: Keyboard Accessibility is Broken
Unable to tab through from left navigation to tab on the right. Was working in previous versions.

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #258 

#### Changelog

**New**

- Adds tab index to side navigation to make sure its keyboard accessible
- Adds skip to content link

**Testing**

Test side nav with keyboard and make sure it works

cc @bocampbell

### CODE REVIEW

File: src/components/SideNav/SideNavItem.js [hunk 1]
```diff
@@ -69,11 +69,16 @@ export default class SideNavItem extends React.Component {
         return '';
       }
 
+      console.log(this.state.open);
```
Comment (asudoh) [inline src/components/SideNav/SideNavItem.js]: Did you mean to remove this line...?
